version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_kotlin_notebook
    ports:
      - "6333:6333"  # HTTP
      - "6334:6334"  # gRPC

volumes:
  minio-data:

networks:
  internal:
    driver: bridge
